vich_uploader:
    db_driver: orm

    mappings:
        theme_image:
            uri_prefix: /uploads/images/themes
            upload_destination: '%kernel.project_dir%/public/uploads/images/themes'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        support_image:
            uri_prefix: /uploads/images/themes
            upload_destination: '%kernel.project_dir%/public/uploads/images/themes'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        collection_image:
            uri_prefix: /uploads/images/collections
            upload_destination: '%kernel.project_dir%/public/uploads/images/collections'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        college_image:
            uri_prefix: /uploads/images/colleges
            upload_destination: '%kernel.project_dir%/public/uploads/images/colleges'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        article_images:
            uri_prefix: /uploads/images/articles
            upload_destination: '%kernel.project_dir%/public/uploads/images/articles'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        article_docs:
            uri_prefix: /uploads/images/articles
            upload_destination: '%kernel.project_dir%/public/uploads/images/articles'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer